#!/usr/bin/env python3
"""
build_the_cove_boundary.py
--------------------------
LIVE GIS/OSM pipeline for The Cove (Deerfield Beach, FL) planning boundary.

This is the script that actually SNAPS the boundary to real-world geometry. It
takes the street-respecting scaffold (from generate_boundary_files.py) and pulls
each of its edge vertices onto the true geometry of:

  - North : Hillsboro Boulevard          (OSM road centerline)
  - West  : US-1 / Federal Highway        (OSM road centerline)
  - East  : Intracoastal Waterway / canals (OSM water edge)
  - South : Lighthouse Point municipal line (OSM/ArcGIS admin boundary)

then re-assembles, validates, simplifies, and exports KML + GeoJSON + CSV.

------------------------------------------------------------------------------
REQUIRES NETWORK EGRESS to ArcGIS Online, Broward County GIS, and OSM/Overpass.
It will NOT run in a sandbox whose policy blocks those hosts (that is exactly
why the committed outputs were generated by the offline generate_boundary_files.py
instead — see source_notes.md). Run this on your machine, or in a session whose
egress policy allows the endpoints below.
------------------------------------------------------------------------------

Install:
    pip install geopandas shapely osmnx requests pandas pyogrio

Run:
    python build_the_cove_boundary.py
"""

import sys

import requests  # noqa: F401  (used by arcgis_query)

try:
    import osmnx as ox
    import geopandas as gpd  # noqa: F401
    from shapely.geometry import Polygon, LineString, MultiLineString, box
    from shapely.geometry import Point
    from shapely.ops import nearest_points, unary_union, linemerge
except Exception as e:  # pragma: no cover
    print("Missing geo stack:", e)
    print("Install with: pip install geopandas shapely osmnx requests pandas pyogrio")
    sys.exit(1)

import generate_boundary_files as gbf  # reuse scaffold + exporters

# --- Area of interest (from the request) --------------------------------------
BBOX = dict(north=26.32050, south=26.29775, west=-80.09950, east=-80.07600)
AOI = box(BBOX["west"], BBOX["south"], BBOX["east"], BBOX["north"])

# Max distance (degrees, ~111 km/deg) a scaffold vertex may be pulled to a real
# feature. Guards against snapping to the wrong far-away geometry. ~0.0025 deg ~ 275 m.
SNAP_MAX_DEG = 0.0025

# Optional ArcGIS REST layers. Verify/replace URLs against the live services
# (Broward County GIS / GeoHub, City of Deerfield Beach). OSM is the primary path,
# so the pipeline still works if these are left as None.
ARCGIS_MUNI_BOUNDARIES_URL = None  # e.g. ".../MapServer/<id>/query" for municipal boundaries
ARCGIS_ROADS_URL = None            # e.g. Broward road centerlines FeatureServer
ARCGIS_WATER_URL = None            # e.g. Broward hydrography / waterways


# ---------------------------------------------------------------------------
# Data fetch helpers
# ---------------------------------------------------------------------------
def arcgis_query(url, where="1=1"):
    """Query an ArcGIS REST feature layer, return GeoJSON dict (or None)."""
    if not url:
        return None
    params = {
        "where": where, "outFields": "*", "outSR": "4326",
        "geometry": f'{BBOX["west"]},{BBOX["south"]},{BBOX["east"]},{BBOX["north"]}',
        "geometryType": "esriGeometryEnvelope", "inSR": "4326",
        "spatialRel": "esriSpatialRelIntersects", "f": "geojson",
    }
    r = requests.get(url, params=params, timeout=60)
    r.raise_for_status()
    return r.json()


def osm_lines(tags):
    """Return a merged shapely (Multi)LineString of OSM features matching tags, clipped to AOI."""
    try:
        gdf = ox.features_from_polygon(AOI, tags=tags)
    except Exception as e:
        print(f"  ! OSM fetch failed for {tags}: {e}")
        return None
    if gdf is None or gdf.empty:
        return None
    geoms = []
    for g in gdf.geometry:
        if g is None:
            continue
        if g.geom_type in ("LineString", "MultiLineString"):
            geoms.append(g)
        elif g.geom_type in ("Polygon", "MultiPolygon"):
            geoms.append(g.boundary)  # use the land/water interface
    if not geoms:
        return None
    merged = unary_union(geoms).intersection(AOI)
    try:
        merged = linemerge(merged)
    except Exception:
        pass
    return merged


def named_road(name_substr):
    """OSM road centerline whose name contains name_substr (case-insensitive)."""
    try:
        gdf = ox.features_from_polygon(AOI, tags={"highway": True})
    except Exception as e:
        print(f"  ! OSM road fetch failed: {e}")
        return None
    if gdf is None or gdf.empty or "name" not in gdf.columns:
        return None
    m = gdf["name"].fillna("").str.contains(name_substr, case=False)
    # also match US-1 by ref
    if "ref" in gdf.columns:
        m = m | gdf["ref"].fillna("").str.contains(name_substr, case=False)
    sub = gdf[m]
    if sub.empty:
        return None
    lines = [g for g in sub.geometry if g is not None and "Line" in g.geom_type]
    if not lines:
        return None
    return linemerge(unary_union(lines).intersection(AOI))


def lighthouse_point_boundary():
    """North edge of Lighthouse Point ~ south edge of The Cove (admin boundary)."""
    try:
        gdf = ox.geocode_to_gdf("Lighthouse Point, Florida, USA")
        return gdf.geometry.iloc[0].boundary.intersection(AOI)
    except Exception as e:
        print(f"  ! Lighthouse Point boundary fetch failed: {e}")
        return None


# ---------------------------------------------------------------------------
# Snapping
# ---------------------------------------------------------------------------
def snap_vertices(vertices, target):
    """Pull each (lon,lat) onto the nearest point of `target` (if within SNAP_MAX_DEG)."""
    if target is None or target.is_empty:
        return vertices  # nothing to snap to -> keep scaffold
    out = []
    for lon, lat in vertices:
        pt = Point(lon, lat)
        try:
            snapped = nearest_points(target, pt)[0]
        except Exception:
            out.append([lon, lat]); continue
        if pt.distance(snapped) <= SNAP_MAX_DEG:
            out.append([round(snapped.x, 6), round(snapped.y, 6)])
        else:
            out.append([lon, lat])  # too far -> keep scaffold vertex
    return out


def edge_slice(name):
    a, b = gbf.EDGE_RANGES[name]
    return [list(p) for p in gbf.SCAFFOLD[a:b]]


def build_ring():
    print("Fetching real-world geometry (OSM / ArcGIS)...")
    hillsboro = named_road("Hillsboro")
    federal = named_road("Federal") or named_road("US 1") or named_road("US-1")
    water = osm_lines({"natural": "water"}) or osm_lines({"waterway": True})
    south = lighthouse_point_boundary()
    if ARCGIS_MUNI_BOUNDARIES_URL:
        print("  (ArcGIS municipal boundaries configured; verify layer covers Lighthouse Point)")

    print("Snapping scaffold edges to real features...")
    north = snap_vertices(edge_slice("north"), hillsboro)
    east = snap_vertices(edge_slice("east"), water)
    south_e = snap_vertices(edge_slice("south"), south)
    west = snap_vertices(edge_slice("west"), federal)

    for label, snapped, target in [
        ("north/Hillsboro", north, hillsboro), ("east/water", east, water),
        ("south/muni", south_e, south), ("west/US-1", west, federal),
    ]:
        state = "SNAPPED" if target is not None and not target.is_empty else "scaffold (no data)"
        print(f"  {label:20s}: {state} ({len(snapped)} pts)")

    ring = north + east + south_e + west
    if ring[0] != ring[-1]:
        ring.append(ring[0])
    poly = Polygon(ring)
    if not poly.is_valid:
        poly = poly.buffer(0)
        if poly.geom_type == "MultiPolygon":
            poly = max(poly.geoms, key=lambda g: g.area)
    poly = poly.simplify(gbf.SIMPLIFY_TOL_DEG, preserve_topology=True)
    return [[round(x, 6), round(y, 6)] for x, y in poly.exterior.coords], poly


def main():
    ring, poly = build_ring()

    # Update provenance to reflect that this run used live GIS geometry.
    gbf.BOUNDARY_PROPS["boundary_type"] = "GIS-snapped planning boundary"
    gbf.BOUNDARY_PROPS["official_status"] = (
        "unofficial - edges snapped to OSM/ArcGIS features; no official 'The Cove' polygon exists"
    )

    gbf.write_kml("the_cove_deerfield_beach_gis_boundary.kml", ring)
    gbf.write_geojson("the_cove_deerfield_beach_gis_boundary.geojson", ring)
    gbf.write_csv("boundary_reference_points.csv")

    acres, sq_mi, _ = gbf.polygon_area_acres(ring)
    print("\n=== QA (GIS-snapped) ===")
    print(f"vertices : {len(ring)} | valid: {poly.is_valid} | simple: {poly.is_simple}")
    print(f"area     : {acres:,.1f} acres | {sq_mi:.3f} sq mi")
    print("Wrote KML, GeoJSON, CSV. Review against a basemap before use.")


if __name__ == "__main__":
    main()
